// Generated by Wrangler on Sat Jul 20 2024 18:44:54 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	DB: D1Database;
	AI: Ai;
}
